### ISSUE TITLE
apt-get update complains about not being passed -y

### ISSUE THREAD

**Issue by johannes-graeter** [CreMindES/whalelint#53]
Thanks for the great work Tamas!
apt-get update && apt-get install --no-install-recommends -y ...
Complains about -y not being passed to update, also the install has still a warning to add --no-install-recommends, although being fixed.

**Comment by CreMindES** [comment]
Yep, silly bug, thanks for raising it @johannes-graeter!

**Comment by CreMindES** [comment]
@johannes-graeter I've just publish the fix on the VSCode Marketplace ; )

**Comment by johannes-graeter** [comment]
Nice one. I trust you and Close the issued then ;)
